spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql:///1901_shop
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:com/qf/dao/mapper/*.xml
  type-aliases-package: com.qf.entity
